### ISSUE TITLE
HoloLens system keyboard

### ISSUE THREAD

**Issue by Vincent-zhai-github** [vuplex/hololens-webview-example#1]
Can the input in the web page call the system keyboard of hololens?

**Comment by BinaryNate** [comment]
Hi, @Vincent-zhai-github 👋. Thank you for your interest! I'll answer your question below. In the future, for 3D WebView questions that aren't specific to this example project, please contact me through [the contact page](https://vuplex.com/contact) instead.

The default Hololens system keyboard doesn't work well with XAML type applications because it causes the app to leave immersion, but MRTK added a new [NonNativeKeyboard](https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.Experimental.UI.NonNativeKeyboard.html#events) component that can be used instead. NonNativeKeyboard is like the default system keyboard, except it avoids the limitation I described with XAML applications. [This blog article](https://localjoost.github.io/migrating-to-mrtk2-using-non-native/) provides more info about NonNativeKeyboard, and [this support article](https://support.vuplex.com/articles/how-to-use-a-third-party-keyboard) describes how to use 3rd party keyboards with 3D WebView. I also have a feature request to update this project to use NonNativeKeyboard, and I added you to its waitlist so that I will send you an update here when I do that in the future.
